---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname_short }}/libvirt/private_key"
  children:
    ipa:
      hosts:
        ipa.poc.internal:
          ansible_host: 192.168.56.11
    keycloak:
      hosts:
        keycloak.poc.internal:
          ansible_host: 192.168.56.12
