---
- name: Configure common baseline
  hosts: all
  become: true
  roles:
    - common

- name: Deploy FreeIPA server
  hosts: ipa
  become: true
  roles:
    - ipaserver

- name: Deploy Keycloak
  hosts: keycloak
  become: true
  roles:
    - keycloak
